version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: traffic_backend
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./src:/src
      - ./data:/data
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: trafficdb
      DB_USER: postgres
      DB_PASS: postgres
      WEATHER_API_KEY: bfa54e11161748918ff230153251610
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: traffic_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: traffic_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: traffic_pass
      POSTGRES_DB: trafficdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
